language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc
  - sudo easy_install cpp-coveralls
script: Scripts/travis-build.sh "Collector"
after_success: Scripts/coveralls.rb --extension m --exclude-folder Collector/Pods --exclude-folder Collector/Tests